spring:
  datasource:
    url: jdbc:sqlserver://java-azure-sqldb-server-103.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;  
    username: satyam_azure
    password: patel@20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080

